### ISSUE TITLE
Подпись к результатам экзаменов

### ISSUE THREAD

**Issue by storkvist** [mgup/hq#161]
Графика
Дизайн
Журналистика

К прохождению дальнейших вступительных испытаний (потом - к участию в конкурсе) допускаются поступающие, набравшие 40 и более баллов по дополнительным вступительным испытаниям

**Comment by Fallmist** [comment]
Журналистика
Собеседование id = 61
Сочинение id = 59
***
Дизайн
Декоративно-шрифтовая id = 57
Рисунок и колористика id = 62

***
Графика
Иллюстрация id = 58
Рисунок и живопись id = 64
